services:
  backend:
    build:
      context: ./DiningReviewRestaurantSpring
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    networks:
      - dining-network

  frontend:
    build:
      context: ./DiningReviewRestaurantReact
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dining-network

  db:
    image: postgres:15-alpine
    container_name: dining-db
    environment:
      POSTGRES_DB: diningdb
      POSTGRES_USER: dininguser
      POSTGRES_PASSWORD: diningpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dining-network

networks:
  dining-network:
    driver: bridge

volumes:
  postgres-data: