kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dining-review-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80 
    protocol: TCP
- role: worker
- role: worker